import { Outfit } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./StoreProvider";

const outfit = Outfit({ subsets: ["latin"], weight: ["300", "400", "500"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased text-gray-700`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
